# Generated by Django 5.0.6 on 2024-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_candidateprofile_profile_picture_skill_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='hiring_for_roles',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='employment_types',
            field=models.ManyToManyField(blank=True, null=True, to='api.employmenttype'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='job_locations',
            field=models.ManyToManyField(blank=True, null=True, to='api.joblocation'),
        ),
    ]
